### ISSUE TITLE
[Feature request] Pass github credentials as container variables

### ISSUE THREAD

**Issue by nmenant** [f5devcentral/f5-super-netops-container#1]
it would be pretty useful to be able to push our github credentials when we start the container. Github is likely to be something a lot of people will leverage with the supernetops container so facilitating its usage would be great

**Comment by 0xHiteshPatel** [comment]
Set the following env variables via -e or --env-file option to docker run:
SNOPS_GIT_USERNAME
SNOPS_GIT_PASSWORD
SNOPS_GIT_HOST
