### ISSUE TITLE
updateRepos Failing - Investigating

### ISSUE THREAD

**Issue by stjbrown** [f5devcentral/f5-super-netops-container#17]
Becoming self-aware...
[cloneGitRepos] Retrieving repository list from https://github.com/f5devcentral/f5-super-netops-container.git#master
[updateRepos] Processing /tmp/snops-repo/images/base/fs/etc/snopsrepo.d/base.json
[updateRepos] Processing /tmp/user_repos.json
[updateRepos][error] Open of file "/tmp/user_repos.json" failed: [Errno 2] No such file or directory: '/tmp/user_repos.json'
[cloneGitRepos] Loading repositories from /home/snops/repos.json
[cloneGitRepos][error] Open of file "/home/snops/repos.json" failed: [Errno 2] No such file or directory: '/home/snops/repos.json

**Comment by jmcalalang** [comment]
@stjbrown do you have the pull string for me? this looks like you're pulling :latest or your missing the tailing "-container"

did you try: docker run -p 8080:80 -p 2222:22 -it f5devcentral/f5-super-netops-container:base 

thats launching right now for me. here is also the hub page for tags:
https://hub.docker.com/r/f5devcentral/f5-super-netops-container/tags/

**Comment by jmcalalang** [comment]
```
docker run -p 8080:80 -p 2222:22 -it f5devcentral/f5-super-netops-container:base
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Reticulating splines...
Becoming self-aware...
[cloneGitRepos] Retrieving repository list from https://github.com/f5devcentral/f5-super-netops-container.git#master
[updateRepos] Processing /tmp/snops-repo/images/base/fs/etc/snopsrepo.d/base.json
[updateRepos] Processing /tmp/user_repos.json
[cloneGitRepos] Loading repositories from /home/snops/repos.json
[cloneGitRepos] Found 6 repositories to clone...
[cloneGitRepos][1/6] Cloning f5-sphinx-theme#master from https://github.com/f5devcentral/f5-sphinx-theme.git
[cloneGitRepos][1/6]  Installing f5-sphinx-theme#master
[cloneGitRepos][2/6] Cloning f5-super-netops-container#master from https://github.com/f5devcentral/f5-super-netops-container.git
[cloneGitRepos][2/6]  Installing f5-super-netops-container#master
[cloneGitRepos][3/6] Cloning f5-application-services-integration-iApp#develop from https://github.com/F5Networks/f5-application-services-integration-iApp.git
[cloneGitRepos][3/6]  Installing f5-application-services-integration-iApp#develop
[cloneGitRepos][4/6] Cloning f5-postman-workflows#develop from https://github.com/0xHiteshPatel/f5-postman-workflows.git
[cloneGitRepos][4/6]  Installing f5-postman-workflows#develop
[cloneGitRepos][5/6] Cloning f5-automation-labs#master from https://github.com/f5devcentral/f5-automation-labs.git
[cloneGitRepos][5/6]  Installing f5-automation-labs#master
[cloneGitRepos][6/6] Cloning ultimate-vimrc#master from https://github.com/amix/vimrc.git
                                .----------.
                               /          /
                              /   ______.'
                        _.._ /   /_
                      .' .._/      '''--.
                      | '  '___          `.
                    __| |__    `'.         |
                   |__   __|      )        |
                      | | ......-'        /
                      | | \          _..'`
                      | |  '------'''
                      | |                      _
                      |_|                     | |
 ___ _   _ _ __   ___ _ __          _ __   ___| |_ ___  _ __  ___
/ __| | | | '_ \ / _ \ '__| ______ | '_ \ / _ \ __/ _ \| '_ \/ __|
\__ \ |_| | |_) |  __/ |   |______|| | | |  __/ || (_) | |_) \__ \
|___/\__,_| .__/ \___|_|           |_| |_|\___|\__\___/| .__/|___/
          | |                                          | |
          |_|                                          |_|

Welcome to the f5-super-netops Container.  This container has the following
services running:

 SSH  tcp/22
 HTTP tcp/80

To access these services you may need to remap ports on your host to the
local container using the command:

 docker run -p 8080:80 -p 2222:22 -it f5devcentral/f5-super-netops

From the HOST perspective, this results in:

 localhost:2222 -> f5-super-netops:22
 localhost:8080 -> f5-super-netops:80

You can then connect using the following:

 HTTP: http://localhost:8080
 SSH:  ssh -p 2222 snops@localhost

Default Credentials:

 snops/default
 root/default

Go forth and automate!

(you can now detach by using Ctrl+P+Q)
```

**Comment by stjbrown** [comment]
Failing with this or any tag used. 



[stbrown@localhost ~]$ sudo docker run -p 8080:80 -p 2222:22 -it f5devcentral/f5-super-netops-container:base
Unable to find image 'f5devcentral/f5-super-netops-container:base' locally
Trying to pull repository docker.io/f5devcentral/f5-super-netops-container ...
base: Pulling from docker.io/f5devcentral/f5-super-netops-container

2aecc7e1714b: Already exists
3ad1c3856820: Already exists
144530f524f4: Already exists
e1d7e4e642e4: Already exists
c8cc4f32e72e: Already exists
88ba8518d871: Already exists
640b2484b4e2: Already exists
9ab92d3b8f09: Already exists
48c28f119727: Already exists
29ad12ef4bc9: Already exists
ec786b8ea169: Already exists
0bc679386183: Already exists
d8fec027880f: Already exists
5875faa91ba7: Already exists
Digest: sha256:ecdbcdf1fd46c63a00b9685d3790b40eccdd0c9e97d86d1b9acc2bc32ff7c519
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Reticulating splines...
Becoming self-aware...
[cloneGitRepos] Retrieving repository list from https://github.com/f5devcentral/f5-super-netops-container.git#master
[updateRepos] Processing /tmp/snops-repo/images/base/fs/etc/snopsrepo.d/base.json
[updateRepos] Processing /tmp/user_repos.json
[updateRepos][error] Open of file "/tmp/user_repos.json" failed: [Errno 2] No such file or directory: '/tmp/user_repos.json'
[cloneGitRepos] Loading repositories from /home/snops/repos.json
[cloneGitRepos][error] Open of file "/home/snops/repos.json" failed: [Errno 2] No such file or directory: '/home/snops/repos.json'
                                .----------.
                               /          /
                              /   ______.'
                        _.._ /   /_
                      .' .._/      '''--.
                      | '  '___          `.
                    __| |__    `'.         |
                   |__   __|      )        |
                      | | ......-'        /
                      | | \          _..'`
                      | |  '------'''
                      | |                      _
                      |_|                     | |
 ___ _   _ _ __   ___ _ __          _ __   ___| |_ ___  _ __  ___
/ __| | | | '_ \ / _ \ '__| ______ | '_ \ / _ \ __/ _ \| '_ \/ __|
\__ \ |_| | |_) |  __/ |   |______|| | | |  __/ || (_) | |_) \__ \
|___/\__,_| .__/ \___|_|           |_| |_|\___|\__\___/| .__/|___/
          | |                                          | |
          |_|                                          |_|

Welcome to the f5-super-netops-container.  This image has the following
services running:

 SSH  tcp/22
 HTTP tcp/80

To access these services you may need to remap ports on your host to the
local container using the command:

 docker run -p 8080:80 -p 2222:22 -it f5devcentral/f5-super-netops-container:base

From the HOST perspective, this results in:

 localhost:2222 -> f5-super-netops-container:22
 localhost:8080 -> f5-super-netops-container:80

You can then connect using the following:

 HTTP: http://localhost:8080
 SSH:  ssh -p 2222 snops@localhost

Default Credentials:

 snops/default
 root/default

Go forth and automate!

(you can now detach by using Ctrl+P+Q)

[root@f5-super-netops] [/] #

**Comment by 0xHiteshPatel** [comment]
This looks like a bug.  Not sure how it snuck in.  Looking into it.

**Comment by 0xHiteshPatel** [comment]
Thought this was a bug but it isn't.  I'm not sure why you're seeing this.  Can you execute the following from **within** the container and send the output:

``ls -l /tmp``
``cat /tmp/user-repos.json``

**Comment by stjbrown** [comment]
There is  only a directory in /tmp...

[root@f5-super-netops] [/] # ls -l /tmp 
total 0
drwxr-xr-x    6 root     root           280 Jun 13 11:26 snops-repo
[root@f5-super-netops] [/] #

**Comment by stjbrown** [comment]
Seems like an odd issue on my centos vm. I had an older version of the container that worked before tryin the new one, but even after removing all of my old images this still failed. I was able to run the new on a different vm so seems to just be this one VM.
