### ISSUE TITLE
jenkins image issue - doesn't start properly

### ISSUE THREAD

**Issue by nmenant** [f5devcentral/f5-super-netops-container#18]
if i start a jenkins super netops container , it dies after a minute on its own: 

i launch my container with the following command: 

`sudo docker run --detach --hostname jenkins.my-lab -p 1080:8080 -p 1022:22 -p 50000:50000 --name jenkins  --volume /Users/menant/projects/containers_vol/jenkins/:/var/jenkins_home f5devcentral/f5-super-netops-container:jenkins`

logs are not really helpful here: 
nico-laptop:jenkins menant$ sudo docker logs jenkins
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
...........
...........
Go forth and automate!

(you can now detach by using Ctrl+P+Q)

/snopsboot/start exited 0
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
nico-laptop:jenkins menant$

if i try to connect to my jenkins web interface, i get the following error: 

http://jenkins.my-lab:1080/

AWT is not properly configured on this server. Perhaps you need to run your container with "-Djava.awt.headless=true"? See also: https://jenkins.io/redirect/troubleshooting/java.awt.headless

java.lang.UnsatisfiedLinkError: /usr/lib/jvm/java-1.8-openjdk/jre/lib/amd64/libfontmanager.so: Error relocating /usr/lib/jvm/java-1.8-openjdk/jre/lib/amd64/libfontmanager.so: AWTFontDefaultChar: symbol not found
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1845)
       .........
       .........

i tried a few thing : 

- make sure that my host jenkins folder is owned by uid 1001 
- run this: 

`sudo docker run --detach --hostname jenkins.my-lab -p 1080:8080 -p 1022:22 -p 50000:50000 --name jenkins --env JAVA_OPTS=-Djava.awt.headless=true --volume /Users/menant/projects/containers_vol/jenkins/:/var/jenkins_home f5devcentral/f5-super-netops-container:jenkins`

any ideas ?

**Comment by s-archer** [comment]
I have an identical issue when deploying with RedHat Openshift.  I wonder if it's related to the last line of the /snops/start file: '/bin/bash --login'.

When I run in native docker, on the same machine it works fine.  When deployed via OpenShift (with root privileges, which are required) I get the following logs in the deployed pod:

...
Go forth and automate!
(you can now detach by using Ctrl+P+Q)
/snopsboot/start exited 0
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.


This causes the pod to enter a 'CrashLoopBackOff' state:


[root@ip-10-1-20-4 centos]# oc describe pod f5-super-netops-container-1-lfhb7
Name:			f5-super-netops-container-1-lfhb7
Namespace:		my-project
Security Policy:	anyuid
Node:			ip-10-1-20-9.us-west-2.compute.internal/10.1.20.9
Start Time:		Thu, 06 Jul 2017 15:01:03 +0000
Labels:			app=f5-super-netops-container
			deployment=f5-super-netops-container-1
			deploymentconfig=f5-super-netops-container
Status:			Running
IP:			10.130.0.44
Controllers:		ReplicationController/f5-super-netops-container-1
Containers:
  f5-super-netops-container:
    Container ID:	docker://0cd5951c7a70772b916febb77487027cc7c6956ac3f6423358f6b0d6bf192951
    Image:		f5devcentral/f5-super-netops-container@sha256:fa08fe42a1529f0bdc4ca3e6af3a09e179cb059ea72c45b4768aa4393e952c1f
    Image ID:		docker-pullable://docker.io/f5devcentral/f5-super-netops-container@sha256:fa08fe42a1529f0bdc4ca3e6af3a09e179cb059ea72c45b4768aa4393e952c1f
    Ports:		22/TCP, 80/TCP
    State:		Waiting
      Reason:		CrashLoopBackOff
    Last State:		Terminated
      Reason:		Completed
      Exit Code:	0
      Started:		Thu, 06 Jul 2017 15:22:48 +0000
      Finished:		Thu, 06 Jul 2017 15:22:52 +0000
    Ready:		False
    Restart Count:	9
    Volume Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-t23gk (ro)
    Environment Variables:	<none>
Conditions:
  Type		Status
  Initialized 	True
  Ready 	False
  PodScheduled 	True
Volumes:
  default-token-t23gk:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-t23gk
QoS Class:	BestEffort
Tolerations:	<none>
Events:


Other images deployed in OpenShift work correctly.

**Comment by 0xHiteshPatel** [comment]
This looks like an issue with the latest alpine image:

https://github.com/jenkinsci/docker/issues/508

Looking into pinning the version to alpine-3.5 for now until this is resolved in alpine-3.6

**Comment by 0xHiteshPatel** [comment]
This should be fixed now... the develop-jenkins image in docker hub has been updated.  

@nmenant @s-archer Please update/test using:

``docker pull f5devcentral/f5-super-netops-container:develop-jenkins``

`` docker run -p 8080:80 -p 2222:22 -p 8081:8080 -p 50000:50000 --rm -it -e SNOPS_GH_BRANCH=develop f5devcentral/f5-super-netops-container:develop-jenkins``

*Connect to http://localhost:8081*

**Comment by adam-f5** [comment]
Repository Archived
