### ISSUE TITLE
f5-newman-Wrapper - not loading the env file generated by a previous collection

### ISSUE THREAD

**Issue by nmenant** [f5devcentral/f5-super-netops-container#22]
Hi,

trying to use the f5-new-wrapper and i cannot make it load the environment file generated by a previous wrapper. 

I have 2 wrappers: 
1- Wrapper_BIGIQ_LM_Create_License_Pool.json   : it creates a license pool on BIG-IQ LM and also activate a regkey into it
2- Wrapper_BIGIQ_LM_License_BIGIP.json : it licenses a BIG-IP based on the previous license pool/regkey created. 

to assign the license to the BIG-IP, i need to re-use the environment variable created in the first wrapper. To do so i use this in my first wrapper configuration: 
"envOutputFile":"Wrapper_BIGIQ_LM_Create_License_Pool-env.json",

I use this in my second wrapper to try to load this env file: 
"globalVarsIncludeFile": "./Wrapper_BIGIQ_LM_Create_License_Pool-env.json", 

When i trigger the first wrapper, i can validate that Wrapper_BIGIQ_LM_Create_License_Pool-env.json gets properly populated. For example: 
```
{
      "type": "any",
      "value": "8ffefeb6-0829-4435-a7e7-fd41655bf01a",
      "key": "license-pool-id"
    },
```

The issue is when i trigger the 2nd wrapper, it isn't using any of the variables define in the file. you see this for example during the wrapper process:

`POST https://192.168.143.31/mgmt/cm/device/licensing/pool/regkey/licenses/{{license-pool-id}}/offerings/{{bigip-regkey}}/members [400 Error processing request, 625B, 7ms]`

Here we can see that license-pool-id has not been replaced by the variable defined in the relevant env file. If i check Wrapper_BIGIQ_LM_License_BIGIP-env.json, we can see that the only variables defined here are the ones defined in the wrapper itself. Not the variables defined in the previous wrapper env file. 
[Wrapper_BIGIQ_LM_Create_License_Pool-env.json.txt](https://github.com/f5devcentral/f5-super-netops-container/files/1094758/Wrapper_BIGIQ_LM_Create_License_Pool-env.json.txt)
[Wrapper_BIGIQ_LM_Create_License_Pool.json.txt](https://github.com/f5devcentral/f5-super-netops-container/files/1094757/Wrapper_BIGIQ_LM_Create_License_Pool.json.txt)
[Wrapper_BIGIQ_LM_License_BIGIP-env.json.txt](https://github.com/f5devcentral/f5-super-netops-container/files/1094760/Wrapper_BIGIQ_LM_License_BIGIP-env.json.txt)
[Wrapper_BIGIQ_LM_License_BIGIP.json.txt](https://github.com/f5devcentral/f5-super-netops-container/files/1094759/Wrapper_BIGIQ_LM_License_BIGIP.json.txt)

i tried a few things but nothing helped: 

- Shorten the name of the 
- Remove some variable like the eula variable that is pretty large
- tried to store the env file somewhere else. 

Couldn't find any log files to try to track the processing. 

Any idea ?

**Comment by 0xHiteshPatel** [comment]
Can you run again using the ``-l 10`` argument.  This will turn on verbose logging.  You can attach the log here or send to me directly.

**Comment by nmenant** [comment]
Attached.



Nicolas Ménant | Global Solution Architect - Sales
D +33 1 41 44 89 50   M +33 6 09 42 10 68
f5.com<https://www.f5.com/> | synthesis.f5.com<https://synthesis.f5.com/>
[witter]<https://twitter.com/f5networks>[inkedIn]<http://www.linkedin.com/company/f5-networks>[acebook]<https://www.facebook.com/f5networksinc>[ouTube]<http://www.youtube.com/f5networksinc>[evCentral]<https://devcentral.f5.com/>
[5 Logo and Tagline]

**Comment by nmenant** [comment]
[Wrapper_BIGIQ_LM_Create_License_Pool-env.json.txt](https://github.com/f5devcentral/f5-super-netops-container/files/1098072/Wrapper_BIGIQ_LM_Create_License_Pool-env.json.txt)
[Wrapper_BIGIQ_LM_Create_License_Pool.json.txt](https://github.com/f5devcentral/f5-super-netops-container/files/1098071/Wrapper_BIGIQ_LM_Create_License_Pool.json.txt)
[Wrapper_BIGIQ_LM_License_BIGIP-env.json.txt](https://github.com/f5devcentral/f5-super-netops-container/files/1098073/Wrapper_BIGIQ_LM_License_BIGIP-env.json.txt)
[Wrapper_BIGIQ_LM_License_BIGIP.json.txt](https://github.com/f5devcentral/f5-super-netops-container/files/1098075/Wrapper_BIGIQ_LM_License_BIGIP.json.txt)
[Wrapper_Create_License_Pool_Output.txt](https://github.com/f5devcentral/f5-super-netops-container/files/1098076/Wrapper_Create_License_Pool_Output.txt)
[Wrapper_License_BIGIP_Output.txt](https://github.com/f5devcentral/f5-super-netops-container/files/1098074/Wrapper_License_BIGIP_Output.txt)





I changed "globalVarsIncludeFile": "/Wrapper_BIGIQ_LM_Create_License_Pool-env.json", to "globalVarsIncludeFile": "Wrapper_BIGIQ_LM_Create_License_Pool-env.json". but it didn’t changed anything. I added the updated wrapper and also the output files for each wrapper triggered:

  1.  Wrapper_BIGIQ_LM_Create_License_Pool.json
  2.  Wrapper_BIGIQ_LM_License_BIGIP.json



Nicolas Ménant | Global Solution Architect - Sales
D +33 1 41 44 89 50   M +33 6 09 42 10 68
f5.com<https://www.f5.com/> | synthesis.f5.com<https://synthesis.f5.com/>
[witter]<https://twitter.com/f5networks>[inkedIn]<http://www.linkedin.com/company/f5-networks>[acebook]<https://www.facebook.com/f5networksinc>[ouTube]<http://www.youtube.com/f5networksinc>[evCentral]<https://devcentral.f5.com/>
[5 Logo and Tagline]


From: Nicolas Menant <N.Menant@F5.com>
Date: Thursday, 22 June 2017 at 17:38
To: f5devcentral/f5-super-netops-container <reply@reply.github.com>, f5devcentral/f5-super-netops-container <f5-super-netops-container@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: Re: [f5devcentral/f5-super-netops-container] f5-newman-Wrapper - not loading the env file generated by a previous collection (#22)

Attached.



Nicolas Ménant | Global Solution Architect - Sales
D +33 1 41 44 89 50   M +33 6 09 42 10 68
f5.com<https://www.f5.com/> | synthesis.f5.com<https://synthesis.f5.com/>
[itter]<https://twitter.com/f5networks>[nkedIn]<http://www.linkedin.com/company/f5-networks>[cebook]<https://www.facebook.com/f5networksinc>[uTube]<http://www.youtube.com/f5networksinc>[vCentral]<https://devcentral.f5.com/>
[Logo and Tagline]

**Comment by adam-f5** [comment]
Repository Archived
