### ISSUE TITLE
fails to run "/snopsboot/cloneGitRepos.py" on CENTOS / RHEL 7

### ISSUE THREAD

**Issue by chen23** [f5devcentral/f5-super-netops-container#27]
Looks like /tmp is empty when running in RHEL/CENTOS 7

docker.io/f5devcentral/f5-super-netops-container   base                981a467f7318        5 weeks ago         206.7 MB
```
$ docker --version
Docker version 1.12.6, build 0fdc778/1.12.6
```

```
[cloneGitRepos] Retrieving repository list from https://github.com/f5devcentral/f5-super-netops-container.git#master
[updateRepos] Processing /tmp/snops-repo/images/base/fs/etc/snopsrepo.d/base.json
[updateRepos] Processing /tmp/user_repos.json
[updateRepos][error] Open of file "/tmp/user_repos.json" failed: [Errno 2] No such file or directory: '/tmp/user_repos.json'
[cloneGitRepos] Loading repositories from /home/snops/repos.json
Traceback (most recent call last):
  File "/snopsboot/cloneGitRepos.py", line 34, in <module>
    repo_file = safe_open(args.filename)
  File "/snopsboot/cloneGitRepos.py", line 20, in safe_open
    print "Open of file '{0}' failed({1}): {2}".format(args[0], e.errno, e.strerror)
TypeError: 'Namespace' object does not support indexing
```

**Comment by johnson5657** [comment]
same here 

[cloneGitRepos] Retrieving repository list from https://github.com/f5devcentral/f5-super-netops-container.git#master
[updateRepos] Processing /tmp/snops-repo/images/jenkins/fs/etc/snopsrepo.d/jenkins.json
[updateRepos]  Processing /tmp/snops-repo/images/base/fs/etc/snopsrepo.d/base.json
[updateRepos] Processing /tmp/user_repos.json
[updateRepos][error] Open of file "/tmp/user_repos.json" failed: [Errno 2] No such file or directory: '/tmp/user_repos.json'
[cloneGitRepos] Loading repositories from /home/snops/repos.json
Traceback (most recent call last):
  File "/snopsboot/cloneGitRepos.py", line 34, in <module>
    repo_file = safe_open(args.filename)
  File "/snopsboot/cloneGitRepos.py", line 20, in safe_open
    print "Open of file '{0}' failed({1}): {2}".format(args[0], e.errno, e.strerror)
TypeError: 'Namespace' object does not support indexing


[root@ansible ~]# cat /etc/redhat-release 
CentOS Linux release 7.7.1908 (Core)

Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-103.git7f2769b.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      7f2769b/1.13.1
 Built:           Sun Sep 15 14:06:47 2019
 OS/Arch:         linux/amd64

**Comment by adam-f5** [comment]
Repository Archived
