### ISSUE TITLE
Pull on Latest isn't grabbing repos/newman

### ISSUE THREAD

**Issue by jmcalalang** [f5devcentral/f5-super-netops-container#8]
FLD-ML-CALALAN1:~ calalang$ docker run -p 8080:80 -p 2222:22 -it f5devcentral/f5-super-netops
Unable to find image 'f5devcentral/f5-super-netops:latest' locally
latest: Pulling from f5devcentral/f5-super-netops
ec37562cf8fa: Pull complete 
065dbb94f1df: Pull complete 
61a6b21a4926: Pull complete 
98aa338aeece: Pull complete 
04c728f639b1: Pull complete 
56ffcc1e9925: Pull complete 
b849c403bc53: Pull complete 
a3f4c6691511: Pull complete 
922ad8a9019e: Pull complete 
88893eb8bd64: Pull complete 
b6c232a411b4: Pull complete 
628a6d0d010a: Pull complete 
Digest: sha256:a51c0b93d596e32ed3f6af68b4411655549295cfeacfb3137fdcf6e82284734f
Status: Downloaded newer image for f5devcentral/f5-super-netops:latest
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Reticulating splines...
Becoming self-aware...
[cloneGitRepos] Retrieving repository list from master
[cloneGitRepos] Found 1 repositories to clone...
[cloneGitRepos][1/1] Cloning 404::404: from 404:
[cloneGitRepos][2/1] Cloning Not:Not from Not
[cloneGitRepos][3/1] Cloning Found:Found from Found

cute little 404 Not Found :)

noticed the changes last night, investigating.

**Comment by jmcalalang** [comment]
from an old clone looks like snops.repo is missing, still investigating.

Contents of old snops:
f5-sphinx-theme;https://github.com/f5devcentral/f5-sphinx-theme.git;master
f5-super-netops-container;https://github.com/f5devcentral/f5-super-netops-container.git;master
f5-application-services-integration-iApp;https://github.com/F5Networks/f5-application-services-integration-iApp.git;develop
f5-postman-workflows;https://github.com/0xHiteshPatel/f5-postman-workflows.git;develop
f5-automation-labs;https://github.com/f5devcentral/f5-automation-labs.git;v2.0

**Comment by jmcalalang** [comment]
repos are moving to what looks like variant folders, f5-super-netops-container/images/base/ looking to see where the call is for the variant folder repo calls

**Comment by jmcalalang** [comment]
[root@f5-super-netops] [/snopsboot] # more cloneGitRepos.sh 
#!/bin/bash

if [ $SNOPS_AUTOCLONE == "0" ]; then
        echo "[cloneGitRepos] Skipping..."
        exit 0
fi

CWD=`pwd`

cd /home/snops
mkdir -p /home/snops/log

if [ ! -f "/home/snops/repos" ]; then
        echo "[cloneGitRepos] Retrieving repository list from ${SNOPS_GH_BRANCH}"
        curl -s -o /home/snops/repos https://raw.githubusercontent.com/f5devcentral/f5-super-netops-container/${SNOPS_GH_BRANCH}/snops.repos
fi

NUMREPOS=`wc -l /home/snops/repos | cut -d' ' -f1`
I=1

echo "[cloneGitRepos] Found $NUMREPOS repositories to clone..."
for i in `cat /home/snops/repos`
do
 REPO=`echo $i | cut -d';' -f1`
 REPOURL=`echo $i | cut -d';' -f2`
 BRANCH=`echo $i | cut -d';' -f3`
 echo "[cloneGitRepos][$I/$NUMREPOS] Cloning $REPO:$BRANCH from $REPOURL"
 git clone -b $BRANCH $REPOURL >> /home/snops/log/cloneGitRepos.log 2>&1
 if [ -f "/snopsboot/repo_install/$REPO" ]; then
  echo "[cloneGitRepos][$I/$NUMREPOS]  Installing $REPO:$BRANCH..."
  cd /home/snops/$REPO && /snopsboot/repo_install/$REPO >> /home/snops/$REPO/repo_install.log 2>&1
 fi
 let I+=1
 cd /home/snops
done

cd $CWD
[root@f5-super-netops] [/snopsboot] # echo $SNOPS_GH_BRANCH
master
[root@f5-super-netops] [/snopsboot] # echo $SNOPS_REPO

[root@f5-super-netops] [/snopsboot] # more /home/snops/
log/   repos  
[root@f5-super-netops] [/snopsboot] # more /home/snops/repos 
404: Not Found

as I'm dissecting it feels like the travis ci piece isn't pulling the images, we only have latest, but if I'm reading this correct we should have:

f5devcentral/f5-super-netops:base
f5devcentral/f5-super-netops:ansible

**Comment by 0xHiteshPatel** [comment]
Try running the image with this:

docker run -p 8080:80 -p 2222:22 --rm -it -e SNOPS_GH_BRANCH=develop f5devcentral/f5-super-netops-container:develop-base

OR

docker run -p 8080:80 -p 2222:22 --rm -it f5devcentral/f5-super-netops-container:base

**Comment by jmcalalang** [comment]
bah, i did this last night FLD-ML-CALALAN1:~ calalang$ docker run -p 8080:80 -p 2222:22 -it f5devcentral/f5-super-netops:base  (Missing container)

Clones work, when you specify the correct piece. 

Clone and PR the readme for the :base? its not a listed item from hub either, only options are latest.

**Comment by 0xHiteshPatel** [comment]
add -container to the image name:

f5devcentral/f5-super-netops**-container**:base 

We have to change the image/repo name to allow CI build/push

**Comment by jmcalalang** [comment]
oh missing the -container was totally my own fault (typing instead of copy..) the :base though, thats something new.

Works:
docker run -p 8080:80 -p 2222:22 --rm -it f5devcentral/f5-super-netops-container:base
